manifest:
  self:
    path: max32664c

  remotes:
    - name: sdk
      url-base: https://github.com/nrfconnect

  group-filter:
    - -optional

  projects:
    - name: sdk-nrf
      remote: sdk
      revision: v3.0.2
      path: nrf
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_ti
          - loramac-node
          - net-tools
          - edtt
          - trusted-firmware-m
          - sof
          - matter
      clone-depth: 1
